/**
 * action in auth
 */
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";

export const SIGN_IN_LOCAL = "SIGN_IN_LOCAL";
export const SIGN_IN_LOCAL_SUCCESS = "SIGN_IN_LOCAL_SUCCESS";
export const SIGN_UP_LOCAL = "SIGN_UP_LOCAL";
export const SIGN_UP_LOCAL_SUCCESS = "SIGN_UP_LOCAL_SUCCESS";

export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";

export const GET_ALL_ROOM = "GET_ALL_ROOM";
export const GET_ALL_ROOM_SUCCESS = "GET_ALL_ROOM_SUCCESS";

export const GET_ROOM = "GET_ROOM";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";

export const GET_BOOKING_ROOM = "GET_BOOKING_ROOM";
export const GET_BOOKING_ROOM_SUCCESS = "GET_BOOKING_ROOM_SUCCESS";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const BOOK_ROOM = "BOOK_ROOM";
export const CANCEL_ROOM = "CANCEL_ROOM";
export const FILTER_ROOM_LIST = "FILTER_ROOM_LIST";

export const FEATURED_ROOM_LIST = "FEATURED_ROOM_LIST";